---
title: "Update Water in Cellar Complaints App"
author: "Farshad Ebrahimi"
date: "`r lubridate::now()`"
output: html_document
params:
    database: "mars_data" 
    write: FALSE #Write changes to database?
---

```{r setup, include=FALSE}

  knitr::opts_chunk$set(echo = TRUE)

  library(DBI)
  library(RPostgreSQL)
  library(RPostgres)
  library(odbc)
  library(RODBC)
  library(dplyr)
  library(tidyr)
  library(sf)
  library(shiny)
  library(lubridate)
  library(knitr)

  MARSDB_con <- dbConnect(odbc(), dsn = params$database)
  cityworksDB_con <- dbConnect(odbc(),
                  Driver = "ODBC Driver 17 for SQL Server",
                  Server = "PWDCWSQLT",
                  Database = "PWD_Cityworks",
                  uid = Sys.getenv("cw_uid"),
                  pwd= Sys.getenv("cw_pwd"))
  GISDB_con <- dbConnect(odbc(),
                  Driver = "ODBC Driver 17 for SQL Server",
                  Server = "PWDGISSQL",
                  Database = "GISDATA",
                  uid = Sys.getenv("gis_uid"),
                  pwd= Sys.getenv("gis_pwd"))
```


```{r Section 1 - Checking for new WIC complaints, new WIC comments, and any other changes, include=FALSE}
    
# gather wic orders and comments from citywork 

   cityworks_workorders <- dbGetQuery(cityworksDB_con, "SELECT wo.WORKORDERID, wo.INITIATEDATE AS WO_INITIATEDATE, wo.LOCATION, wo.WOXCOORDINATE, 
    wo.WOYCOORDINATE, woe.ENTITYUID AS FACILITYID FROM Azteca.WORKORDER wo INNER JOIN 
    Azteca.REQUESTWORKORDER rwo ON wo.WORKORDERID = rwo.WORKORDERID LEFT JOIN 
    Azteca.REQUEST r ON rwo.REQUESTID = r.REQUESTID LEFT JOIN Azteca.WORKORDERENTITY woe ON 
    wo.WORKORDERID = woe.WORKORDERID WHERE 
    ((wo.DESCRIPTION = 'A - PROPERTY INVESTIGATION' AND r.DESCRIPTION = 'WATER IN CELLAR') OR 
    (wo.DESCRIPTION = 'A - LEAK INVESTIGATION' AND r.DESCRIPTION = 'WATER IN CELLAR'))
    ")
   cityworks_cm <- dbGetQuery(cityworksDB_con, "SELECT WORKORDERID, COMMENTS from Azteca.WOCOMMENT" )
   
# gather current wic orders and comments from MARS_Data
   
   wic_workorders <- dbGetQuery(MARSDB_con, "SELECT * FROM fieldwork.wic_workorders ")
   wic_comments <- dbGetQuery(MARSDB_con, "SELECT * FROM fieldwork.wic_comments ")
   
# change the data column format; for some reason anti_join cannot match the dates in POSIXct
   
   wic_workorders$wo_initiatedate <- as.Date(wic_workorders$wo_initiatedate)
   cityworks_workorders$WO_INITIATEDATE <- as.Date(cityworks_workorders$WO_INITIATEDATE)
   
   cityworks_workorders$WORKORDERID <- as.numeric(cityworks_workorders$WORKORDERID)
   cityworks_cm$WORKORDERID <- as.numeric(cityworks_cm$WORKORDERID)
   
# make names consistent    

   names(cityworks_workorders) <- c("workorder_id","wo_initiatedate","location","wo_xcoordinate","wo_ycoordinate","facility_id")
   names (cityworks_cm) <- c("workorder_id","comments")
   
# find the new wic complaint and changed ones in cityworks DB
   
   new_wic <- cityworks_workorders %>% filter(!(workorder_id %in% wic_workorders$workorder_id))
   cityworks_workorders_old <- anti_join(cityworks_workorders, new_wic, by = "workorder_id")
   changed_wic_cityworks <- cityworks_workorders_old  %>%
     anti_join(wic_workorders, by = c("workorder_id","wo_initiatedate","location","wo_xcoordinate","wo_ycoordinate","facility_id")) 
   
# Append the new WIC to wic_workorders
   
   if( nrow(new_wic) > 0 & params$write == TRUE ){
  
  dbWriteTable (MARSDB_con, SQL("fieldwork.wic_workorders"),new_wic,append= TRUE, row.names = FALSE)
     
  }
   
# Update the workorders in wic_workorders that have been changed in cityworks DB 
   
   if(nrow(changed_wic_cityworks) > 0 & params$write == TRUE){
     
     sql_string <- "UPDATE fieldwork.wic_workorders SET wo_initiatedate = '%s', location = '%s',  wo_xcoordinate = %s,wo_ycoordinate= %s,facility_id = '%s' WHERE workorder_id = %s;"
     dbSendStatement(MARSDB_con, paste(sprintf(sql_string, changed_wic_cityworks$wo_initiatedate, changed_wic_cityworks$location,changed_wic_cityworks$wo_xcoordinate,changed_wic_cityworks$wo_ycoordinate,changed_wic_cityworks$facility_id,changed_wic_cityworks$workorder_id), collapse=""))
     
   }
   
# update comments and add new comments to the new workorders
   
   workorders_unique <- select(cityworks_workorders,workorder_id) %>% unique()
   cw_wic_comments <- inner_join(workorders_unique, cityworks_cm, by = "workorder_id")
   cw_wic_comments<- cw_wic_comments %>%
       group_by(workorder_id) %>%
       summarise(comments = toString(sort(unique(comments)))) 
   new_wo_comments <- inner_join(new_wic, cw_wic_comments, by = "workorder_id") %>% select(workorder_id, comments)
   old_wo_comments <-anti_join(cw_wic_comments, new_wo_comments, by = "workorder_id")
   old_wo_comments <-as.data.frame(old_wo_comments)
   
   old_wo_comments$comments <- gsub("[\r\n]", "", old_wo_comments$comments)
   wic_comments$comments <- gsub("[\r\n]", "", wic_comments$comments)

   changed_comments <- anti_join(old_wo_comments, wic_comments, by = c("comments"))
   changed_comments_cityworks <- changed_comments %>% select(workorder_id) %>% inner_join(cw_wic_comments, by = "workorder_id")
   
    if( nrow(new_wo_comments) > 0 & params$write == TRUE ){
      
  dbWriteTable (MARSDB_con, SQL("fieldwork.wic_comments"),new_wo_comments,append= TRUE, row.names = FALSE)
      
    }
   
   
   if(nrow(changed_comments_cityworks) > 0 & params$write == TRUE){
     
     sql_string <- "UPDATE fieldwork.wic_comments SET comments = '%s' WHERE workorder_id = %s;"
     dbSendStatement(MARSDB_con, paste(sprintf(sql_string, changed_comments_cityworks$comments, changed_comments_cityworks$workorder_id), collapse=""))
     
   }
   
```
 The cityworks database has been examined for new water-in-cellar work orders, and also any changes that have been made to the existing work orders. There are `r nrow(new_wic)` new work orders and `r nrow(changed_wic_cityworks)` work orders whose fields have changed. There are also `r nrow(changed_comments_cityworks)` work orders whose comments have been modified.  
 
```{r Section 2- displaying tables of new work orders and changed work orders ,echo=FALSE, results='asis'}

  if (nrow(new_wic) > 0) {

    kable(new_wic, caption = "New Work Orders in Cityworks Database")
    
  }

  if (nrow(changed_wic_cityworks) > 0) {

    kable(nrow(changed_wic_cityworks), caption = "Modified Work Orders in Cityworks Database")
    
  }

```

```{r Section 3- attach parcels to any existing WOs that have no parcels attached ,include=FALSE}

   wo_noparcels <- bind_rows(changed_wic_cityworks, new_wic)
   wic_parcels <- 0

  if (nrow(wo_noparcels) > 0) {
    
     Parcels_Frame <- dbGetQuery(GISDB_con, "SELECT * from GISDATA.GISAD.PWD_PARCELS")
     Parcels_facility_id <- select(Parcels_Frame, FACILITYID)
     Parcels_Address_id <- select(Parcels_Frame, ADDRESS, FACILITYID)
     PARCELS_SPATIAL <- st_read(dsn = "\\\\pwdoows\\oows\\Watershed Sciences\\GSI Monitoring\\09 GIS Data\\PWD_PARCELS ", layer = "PWD_PARCELS")
     st_crs(PARCELS_SPATIAL) = 2272
     wo_noparcels$facility_id<-gsub("\\{(.*)\\}","\\1",as.character(wo_noparcels$facility_id))
  
    
    ##Matching by facility ID
     
    # Inner join the wo_noparcels and Parcels_Addressid ON facility ID
      WOID_FACID_Match <- inner_join (wo_noparcels, Parcels_Address_id  , by = c("facility_id"="FACILITYID"))
    # Get FIRST OUTPUT BASED ON FACILITYID MATCH STORED IN WOID_FAC_UNIQ_REL
      WOID_FAC_UNIQ_REL <- select(WOID_FACID_Match, workorder_id, location, facility_id)
    # Remove the rows that we matched based on the facilityid from the cityworks table 
      wo_noparcels <- anti_join(wo_noparcels, WOID_FACID_Match, by = "workorder_id")
    # Remove the rows that were matched from the Parcels_Address_id table
      Parcels_Address_id <-anti_join(Parcels_Address_id, WOID_FACID_Match, by = c("FACILITYID"="facility_id") )
    # drop the facility id from workorderid as these ids are not meaningful 
      WORKORDER_ID_Location<-  select(wo_noparcels, -facility_id)
      
    ##Matching by address
      
    # Inner join the  WORKORDER_ID_Location with Parcels_Address_id to extract the facility id
      WO_ID_ADDRESS_MATCH <- inner_join(WORKORDER_ID_Location,Parcels_Address_id,by = c("location" = "ADDRESS"))
    # GET SECOND OUTPUT BASED ON FACILITYID MATCH STORED IN WOID_FAC_UNIQ_Add_REL )  
      WOID_FAC_UNIQ_Add_REL <- WO_ID_ADDRESS_MATCH  %>% select(workorder_id, location, facility_id = FACILITYID)  
    # Remove the rows that we were matched based on the address from the cityworkstable 
      wo_noparcels <- anti_join(wo_noparcels, WO_ID_ADDRESS_MATCH, by = "workorder_id")
    # Remove the rows that were matched from the Parcels_Address_id table
      Parcels_Address_id <-anti_join(Parcels_Address_id, WO_ID_ADDRESS_MATCH, by = "FACILITYID" ) 
      
    
   ##Matching by XY coordinates
      
    # Build the spatial object from the XY coordinates in Cityworks
     
      xy_coor <-  c(wo_noparcels[,"wo_xcoordinate"],wo_noparcels[,"wo_ycoordinate"])
      mat_coor <- matrix(data = xy_coor, ncol = 2) %>% na.omit
      WO_SPATIAL <- mat_coor |> 
         as.matrix() |> 
         st_multipoint() |> 
         st_sfc() |> 
         st_cast('POINT')
      st_crs(WO_SPATIAL) <- 2272
      
    # Intersect the Parcel polygons and the points
       WO_PARC_INTERSECT <- st_intersects(WO_SPATIAL, PARCELS_SPATIAL )
   
    # Get the index of intersecting XY coordinates and Parcel polygons
       
       Index_WO <- NULL
       Index_Parcel <- NULL
        for(i in 1:length(WO_PARC_INTERSECT)) {
            temp <- WO_PARC_INTERSECT[[i]]
              if (length(temp) > 0) {
              WO <- rep(i, length(temp))
              Parcel <- temp
              Index_WO <- c(Index_WO, WO )
              Index_Parcel <- c(Index_Parcel, Parcel ) 
              }
         }
      
    # attach the XY coordinate to the Parcel frame to create COORD_MATCHED_TABLE
       
       mat_coor <- data.frame (mat_coor)
       names(mat_coor) <- c("wo_xcoordinate","wo_ycoordinate")
       WO_MATCHED_XY <- mat_coor[Index_WO, ]
       Parcel_Matched_Polyg <- Parcels_Frame[Index_Parcel, ]
       COORD_MATCHED_TABLE <- cbind(Parcel_Matched_Polyg,WO_MATCHED_XY)
       
    # Get workorderid, address, and facilityid (Third output is stored in WOID_Based_XY )
       
       WOID_Based_XY<- wo_noparcels %>% select(workorder_id, wo_initiatedate, location, wo_xcoordinate, wo_ycoordinate) %>% inner_join(COORD_MATCHED_TABLE, by = c("wo_xcoordinate" = "wo_xcoordinate", "wo_ycoordinate" = "wo_ycoordinate")) %>% select(workorder_id, location = ADDRESS, facility_id = FACILITYID) 
       
    # union the matching tables-Final output is in FACID_ADD_XY
     
       FACID_ADD <- union_all (WOID_FAC_UNIQ_REL,WOID_FAC_UNIQ_Add_REL)
       FACID_ADD_XY <- union_all (FACID_ADD, WOID_Based_XY)
       wic_parcels <- unique(FACID_ADD_XY)
       
    # Add the workorder date 
       
       WORKORDER_ID <- dbGetQuery(MARSDB_con, "SELECT * from fieldwork.wic_workorders")
       WORK_DATE <- WORKORDER_ID %>% select(workorder_id, wo_initiatedate)
       wic_parcels <- inner_join(wic_parcels, WORK_DATE, by = "workorder_id") %>% select(workorder_id, location, facility_id, wo_initiatedate)
       
  }
     
    ## write to database
     
     if( !is.null(wic_parcels) & params$write == TRUE ){
      
  dbWriteTable (MARSDB_con, SQL("fieldwork.wic_parcels"),wic_parcels,append= TRUE, row.names = FALSE)
      
    }

```
 
